// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSCyDq_1t6N7GPj74ZObVi4FkyfuYCKts',
    appId: '1:270139657458:web:eda12a5972d279752a946b',
    messagingSenderId: '270139657458',
    projectId: 'shop-app-d00fc',
    authDomain: 'shop-app-d00fc.firebaseapp.com',
    databaseURL: 'https://shop-app-d00fc-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-d00fc.appspot.com',
    measurementId: 'G-XRVKHZ080Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSgn5ksI7SWd3KAPSYAHX9CJTrTf0Jao',
    appId: '1:270139657458:android:ef1c37096f1c6e552a946b',
    messagingSenderId: '270139657458',
    projectId: 'shop-app-d00fc',
    databaseURL: 'https://shop-app-d00fc-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-d00fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmK9AnmnFMHUW2FgL_UMguE9ohHEjL_4',
    appId: '1:270139657458:ios:bcb71bf9a90e768c2a946b',
    messagingSenderId: '270139657458',
    projectId: 'shop-app-d00fc',
    databaseURL: 'https://shop-app-d00fc-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-d00fc.appspot.com',
    iosClientId: '270139657458-0vejnijredpdfqq4qfo15jvq1vu0tf3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
